-- ================================================================
-- ENABLE RLS FOR TECHNICAL_ANALYSES TABLE
-- Purpose: Allow authenticated users to read technical reports
-- Date: 2026-01-06
-- ================================================================

-- Enable RLS on technical_analyses table (if not already enabled)
ALTER TABLE technical_analyses ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Users can read all technical analyses" ON technical_analyses;
DROP POLICY IF EXISTS "Service role can insert technical analyses" ON technical_analyses;
DROP POLICY IF EXISTS "Service role can update technical analyses" ON technical_analyses;

-- Policy: Allow all authenticated users to read technical reports
-- This is needed because reports are accessed via API routes with authenticated sessions
CREATE POLICY "Users can read all technical analyses"
ON technical_analyses
FOR SELECT
TO authenticated
USING (true);

-- Policy: Allow anon role to insert (for N8N webhook)
CREATE POLICY "Service role can insert technical analyses"
ON technical_analyses
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Policy: Allow anon role to update (for N8N webhook)
CREATE POLICY "Service role can update technical analyses"
ON technical_analyses
FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- Add comment for documentation
COMMENT ON TABLE technical_analyses IS 'Technical analysis reports generated by N8N workflows. RLS enabled with public read access for authenticated users.';
